### ISSUE TITLE
Error Running Python Scripts with Overrides: can't run benchmark including algo walker_diaync and env BiskGoalWall-v1

### ISSUE THREAD

**Issue by SuuTTT** [facebookresearch/hsd3#3]
Issue: Error Running Python Scripts with Overrides

Description:
I encountered errors while running the following Python scripts with specific overrides:

1. `python pretrain.py -cn walker_diaync_pretrain`
   Error Message:
   ```
   /opt/conda/envs/hsd3/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
   See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
   ret = run_job(
   Error executing job with overrides: ['checkpoint_path=exp_result_Dyn_pretrain/walker_BiskHurdles-v1/checkpoint.pt', 'visdom.logfile=exp_result_Dyn_pretrain/walker_BiskHurdles-v1/visdom.log', 'env.name=BiskHurdles-v1']
   Traceback (most recent call last):
     File "pretrain.py", line 953, in main
       rdvu_file = f'{cfg.distributed.rdvu_path}/rdvu-{uuid.uuid4()}'
   omegaconf.errors.ConfigAttributeError: Key 'distributed' is not in struct
       full_key: distributed
       object_type=dict

   Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
   ```

2. `python train.py -cn walker_hiro env.name=BiskGoalWall-v1`
   Error Message:
   ```
   Error executing job with overrides: ['checkpoint_path=exp_result_DYN_pretrain/walker_BiskGoalWall-v1/checkpoint.pt', 'visdom.logfile=exp_result_DYN_pretrain/walker_BiskGoalWall-v1/visdom.log', 'env.name=BiskGoalWall-v1']
   Traceback (most recent call last):
     File "train.py", line 544, in main
       setup = setup_training(cfg)
     File "train.py", line 84, in setup_training
       envs = hucc.make_vec_envs(
     File "/home/sudingli/workplace/RL/TPAMI2023/HSD3/hsd3/hucc/envs/wrappers.py", line 420, in make_vec_envs
       envs = AsyncVectorEnv(
     File "/home/sudingli/workplace/RL/TPAMI2023/HSD3/hsd3/hucc/envs/thmp_vector_env.py", line 97, in __init__
       dummy_env = env_fns[0]()
     File "/home/sudingli/workplace/RL/TPAMI2023/HSD3/hsd3/hucc/envs/wrappers.py", line 400, in thunk
       env = gym.make(env_name, **env_args)
     File "/home/sudingli/miniconda3/envs/hsd3/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
       return registry.make(id, **kwargs)
     File "/home/sudingli/miniconda3/envs/hsd3/lib/python3.8/site-packages/gym/envs/registration.py", line 129, in make
       env = spec.make(**kwargs)
     File "/home/sudingli/miniconda3/envs/hsd3/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
       env = cls(**_kwargs)
   TypeError: __init__() got an unexpected keyword argument 'feature_dist'

   Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by jgehring** [comment]
Sorry for the late reply!

1. For DIAYN pre-training, use `train.py` like so: `python train.py -cn walker_diaync_pretrain`

2. On a vanilla checkout, `python train.py -cn walker_hiro env.name=BiskGoalWall-v1` works fine for me. The only environment requiring a `feature_dist` is the HSD3 pre-training environment (CtrlgsPreTrainingEnv). Maybe the error is caused by some changes that were made to the code?

Please let me know if this resolves the issue.
